language: node_js

cache: yarn

script: ""

deploy:
  - provider: npm
    email:
      secure: Nlf6YLi1gnY4ukDxyyweI62TDm0JW2ekwsXycFvhltL4K/A9kUeI9LoKzRwTXNkssXu/ZBfLhlPZOn5v4T2Jpeo+G25jbxN+u3Ti+XXZb/TWaSomUKi6+aCg3oCUdL8WjQSozBTYtCPBlMcA2KlB9zmUO2n58hihl9eRpMdXE4jY3EcJgTWT1rOGA4jyy74/6cCqeMR6bnj7gaQdP2x6OyjVqjO29oEu+z91MZQJwrTfSp/PdDLPltrmUF1eY3L8Bcz1sjJHNIjbJ0JG0I+iZhm/dC70hg4Kf+bY91VBvvaL0e97k+H1MUybYWXabRYvYSNPb/AFlFBCVmpLDnmntQINPQuuzKEqAgn5ziBipO2rJs45MK1e6VAp6P52P0xKBuehm9B6EwR4XiB/nFLcQpdE1AFElzECNwIvij/+VG9jvi89EpCFipnxCW3qxvS5kTdmSTxmFZXktXeMlDCCvfz6AHmfpdXvhCc1lS7BiCUie2FMb2Rq3K4p16D7d3n0C7B+cdWO8RcHhO0IMuNKWuK42tWx4QYoBMjhic+3nThZg4Vu2AtzBh32aJ1isAj2pXVi67yRhN4gyMD2HAoHf6j+Z6Sbe0Ijr9S69PRiPftm+6tOMS4FbVT1CpJA+P2Xek5XX/w/qmoDJ0lPxuEE7zl7f6Wsl7hiQ7zYv1tjzuQ=
    api_key:
      secure: JqKquOmdb/xhheOTUk/pns54MwHqldO7K/zKmDIZ1LCHmDa9MAeFRNc5/n5yF6WaMkm7mJNT1XmjOVMDVCkUyO2TgdCl7yoErK4mFR2vDsWra06uhW2kNQFAVNVN6Dh1vQPBtAQOYwALTYk+1acGV+9lmA3ZpTnaZQRSFvRAFd5jjk8XClGow9VURf6aMhN23h/SHOY4qqRULj5e8bRDKCdBJUF1TI5nKs47A9UMb4RopL6xoIKl0Z6cDS8Ds+82nwJxsB5xVxCM3cEtiAi4/29xRBB4D8YSQjUe+k7KK8SCIEbH45WEfzGQXtVDNuW6a1qi67T3nxQ/BRB3dnRR4SKA+cOOTKyH+PFO6UdoUCShqOqmURtmBwW+bF4UcEESpok0+hr6S0POVUmm/E0Qdjr1j/DXzTdMLzU11+VGdNvd+K7EqhfbFWxG41JqLqKbxPwLxnZuYYjb2Puj+r1FXWqfHNNopBZVSK9nwSpIZtZIRJsuCoU3ociart6a1u/UAaHZvQaWXroGcdl7RMdchlOwX+aStYWwVpidZxBsK8nAJjWGD1/JQLVkmyaZKHjLr2coYH/VAK7B+FszA6XUnPl4GwtYJ1f/XnSKp6rWZOBdBHqn5HUrd5HZglU2VSqCRH4iRYc9uDlH31TdjvImwLPFcYZGUmuIYggdREz3jx8=
    on:
      tags: true
